# Generated by Django 5.2.9 on 2026-01-09 05:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_productvariant_products_pr_reserve_157a26_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_number', models.CharField(db_index=True, help_text='Unique import note number (e.g., IMP-2024-001)', max_length=50, unique=True)),
                ('total_items', models.IntegerField(default=0, help_text='Total number of different variants in this import')),
                ('total_quantity', models.IntegerField(default=0, help_text='Total quantity of all items imported')),
                ('notes', models.TextField(blank=True, help_text='General notes about this import (supplier, reason, etc.)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_notes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Import Note',
                'verbose_name_plural': 'Import Notes',
                'db_table': 'import_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity to import', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit (optional, for accounting purposes)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Notes specific to this item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.importnote', verbose_name='Import Note')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_items', to='products.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Import Note Item',
                'verbose_name_plural': 'Import Note Items',
                'db_table': 'import_note_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive for additions (import, refund), negative for deductions (order)')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Import Stock'), ('ORDER', 'Order Deduction'), ('REFUND', 'Order Refund/Cancel'), ('ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('transaction_id', models.CharField(db_index=True, help_text='Order number, import note number, or adjustment ID', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who performed this action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.productvariant', verbose_name='Product Variant')),
            ],
            options={
                'verbose_name': 'Inventory Log',
                'verbose_name_plural': 'Inventory Logs',
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='importnote',
            index=models.Index(fields=['import_number'], name='import_note_import__ad2f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='importnote',
            index=models.Index(fields=['status', '-created_at'], name='import_note_status_ecce8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importnoteitem',
            unique_together={('import_note', 'variant')},
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['variant', '-created_at'], name='inventory_l_variant_f20174_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_type', '-created_at'], name='inventory_l_transac_e65830_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_id'], name='inventory_l_transac_6b96e3_idx'),
        ),
    ]
