# Generated by Django 5.2.9 on 2026-01-06 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('payment_method', models.CharField(choices=[('vnpay', 'VNPAY'), ('banking', 'Chuyển khoản ngân hàng'), ('cod', 'Thanh toán khi nhận hàng (COD)')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã giao dịch')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền hàng')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Phí vận chuyển')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Giảm giá')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng thanh toán')),
                ('customer_note', models.TextField(blank=True, verbose_name='Ghi chú của khách hàng')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('variant_sku', models.CharField(max_length=100, verbose_name='Mã SKU')),
                ('variant_details', models.JSONField(verbose_name='Chi tiết biến thể')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá đơn vị')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant', verbose_name='Biến thể sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn hàng',
                'verbose_name_plural': 'Sản phẩm trong đơn hàng',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, verbose_name='Trạng thái cũ')),
                ('to_status', models.CharField(max_length=20, verbose_name='Trạng thái mới')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái',
                'verbose_name_plural': 'Lịch sử trạng thái',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address_line1', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('address_line2', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ bổ sung')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện')),
                ('city', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Mã bưu điện')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='Quốc gia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Địa chỉ giao hàng',
                'verbose_name_plural': 'Địa chỉ giao hàng',
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
    ]
