# Generated by Django 5.2.9 on 2026-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('vnpay_qr', 'VNPAY - Quét mã QR'), ('vnpay_card', 'VNPAY - Thẻ ngân hàng'), ('banking', 'Chuyển khoản ngân hàng'), ('cod', 'Thanh toán khi nhận hàng (COD)')], max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
