# Generated by Django 5.2.9 on 2026-01-08 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hủy đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Lý do hủy đơn'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Đơn vị vận chuyển'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirming_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chờ xác nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao thành công'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivering_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu xử lý'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý thất bại'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_notes',
            field=models.JSONField(blank=True, default=dict, help_text='Stores validation results, error messages, and processing details', verbose_name='Chi tiết xử lý'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý thành công'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='Lý do hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian yêu cầu hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tiền thành công'),
        ),
        migrations.AddField(
            model_name='order',
            name='refunding_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu hoàn tiền'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã vận đơn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao hàng (legacy)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('PROCESSING', 'Đang xử lý'), ('PROCESSING_SUCCESS', 'Xử lý thành công'), ('PROCESSING_FAILED', 'Xử lý thất bại'), ('CONFIRMING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('DELIVERING', 'Đang giao hàng'), ('DELIVERED', 'Giao thành công'), ('REFUND_REQUESTED', 'Đã gửi yêu cầu hoàn tiền'), ('REFUNDING', 'Đang hoàn tiền'), ('REFUNDED', 'Đã hoàn tiền'), ('COMPLETED', 'Hoàn thành'), ('CANCELED', 'Đã hủy')], db_index=True, default='PENDING', max_length=30, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='from_status',
            field=models.CharField(max_length=30, verbose_name='Trạng thái cũ'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='to_status',
            field=models.CharField(max_length=30, verbose_name='Trạng thái mới'),
        ),
    ]
