# Generated by Django 5.2.9 on 2026-01-08 15:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_canceled_at_order_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Mã voucher duy nhất (sẽ tự động chuyển thành chữ hoa)', max_length=50, unique=True, verbose_name='Mã voucher')),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết về voucher', verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Phần trăm'), ('FIXED_AMOUNT', 'Số tiền cố định'), ('FREE_SHIPPING', 'Miễn phí vận chuyển')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Phần trăm (1-100) hoặc Số tiền (VNĐ)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Giá trị giảm')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Đơn hàng phải đạt giá trị này để áp dụng voucher', max_digits=10, verbose_name='Giá trị đơn hàng tối thiểu')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Áp dụng cho voucher phần trăm - giới hạn số tiền giảm tối đa', max_digits=10, null=True, verbose_name='Giảm tối đa')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Để trống nếu không giới hạn', null=True, verbose_name='Số lần sử dụng tối đa')),
                ('usage_per_user', models.PositiveIntegerField(default=1, help_text='Số lần tối đa mỗi người dùng có thể sử dụng voucher này', verbose_name='Số lần sử dụng/người dùng')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, help_text='Số lần voucher đã được sử dụng', verbose_name='Đã sử dụng')),
                ('valid_from', models.DateTimeField(help_text='Ngày bắt đầu có hiệu lực', verbose_name='Có hiệu lực từ')),
                ('valid_until', models.DateTimeField(help_text='Ngày hết hạn', verbose_name='Hết hạn')),
                ('is_active', models.BooleanField(default=True, help_text='Tắt để vô hiệu hóa voucher mà không cần xóa', verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='applied_vouchers',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.voucher', verbose_name='Vouchers đã áp dụng'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code'], name='vouchers_code_3d6847_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='vouchers_is_acti_230653_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['-created_at'], name='vouchers_created_dc3f5c_idx'),
        ),
    ]
