# Generated by Django 5.2.9 on 2026-01-07 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('vnpay_qr', 'VNPAY - Quét mã QR'), ('vnpay_card', 'VNPAY - Thẻ ngân hàng'), ('banking', 'Chuyển khoản ngân hàng'), ('cod', 'Thanh toán khi nhận hàng')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Mã giao dịch')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã GD cổng thanh toán')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu phản hồi')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'), models.Index(fields=['order', '-created_at'], name='payments_order_i_cdec7b_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx')],
            },
        ),
    ]
