# Generated by Django 5.2.9 on 2026-01-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('vnpay_qr', 'VNPAY'), ('vnpay_card', 'VNPAY'), ('banking', 'Chuyển khoản ngân hàng'), ('cod', 'Thanh toán khi nhận hàng')], max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
