# Generated by Django 5.2.9 on 2026-01-06 14:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('color', models.CharField(help_text='Frame color (e.g., Black, Gold, Tortoise)', max_length=50)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color code for UI display', max_length=7)),
                ('material', models.CharField(choices=[('acetate', 'Acetate'), ('metal', 'Metal'), ('titanium', 'Titanium'), ('plastic', 'Plastic'), ('wood', 'Wood'), ('mixed', 'Mixed Materials')], default='acetate', max_length=50)),
                ('lens_type', models.CharField(choices=[('clear', 'Clear (No Prescription)'), ('prescription', 'Prescription Ready'), ('polarized', 'Polarized'), ('photochromic', 'Photochromic (Transition)'), ('blue_light', 'Blue Light Filter'), ('sunglasses', 'Sunglasses')], default='clear', max_length=50)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', help_text='Frame size', max_length=20)),
                ('lens_width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bridge_width', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temple_length', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (if on sale)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost for profit calculation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default variant to display for the product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'color', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('sku_prefix', models.CharField(help_text='Prefix for variant SKUs', max_length=50, unique=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('short_description', models.TextField(help_text='Brief product highlight', max_length=500)),
                ('description', models.TextField(help_text='Full product description (supports HTML/Markdown)')),
                ('target_gender', models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Male'), ('female', 'Female'), ('kids', 'Kids')], default='unisex', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price for display', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('original_file', models.FileField(help_text='Original uploaded file (unprocessed)', upload_to='products/originals/%Y/%m/')),
                ('processed_images', models.JSONField(blank=True, default=dict, help_text='URLs/paths to processed image sizes (WebP format)')),
                ('processed_video', models.FileField(blank=True, help_text='Processed video (HLS/MP4)', null=True, upload_to='products/videos/processed/%Y/%m/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='products/videos/thumbnails/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for SEO', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
