# Generated by Django 5.2.9 on 2026-01-08 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reserved_stock',
            field=models.IntegerField(default=0, help_text='Stock reserved for pending orders (not yet deducted)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, help_text='Total physical stock in warehouse', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['reserved_stock'], name='products_pr_reserve_157a26_idx'),
        ),
    ]
