# Generated by Django 5.2.9 on 2026-01-08 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_reserved_stock_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_reserve_157a26_idx',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='reserved_stock',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
