# Generated by Django 5.2.9 on 2026-01-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_products_pr_reserve_157a26_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='Prefix for variant SKUs', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
